version: '3.7'

services:

  redis:
    image: redis:5.0.7
    container_name: pyredis_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./database:/database

  post:
    build: .
    image: pyredis:1.0
    container_name: pyredis_post
    restart: always
    volumes:
      - ./:/pyredis
